Update trigger_kaggle.yml

diff --git a/.github/workflows/trigger_kaggle.yml b/.github/workflows/trigger_kaggle.yml
--- a/.github/workflows/trigger_kaggle.yml
+++ b/.github/workflows/trigger_kaggle.yml
@@ -48,8 +48,4 @@ jobs:
       - name: Submit Notebook to Kaggle  # 提交 Notebook 到 Kaggle
         run: |
           echo "Submitting notebook with title: ${NOTEBOOK_TITLE}"
-          ABSOLUTE_PATH=$(pwd)/${NOTEBOOK_DIR}
-          echo "Absolute path: ${ABSOLUTE_PATH}"
-          echo "Listing files in the directory:"
-          ls -l ${ABSOLUTE_PATH}
-          kaggle kernels push -p "${ABSOLUTE_PATH}" || { echo "Failed to push notebook to Kaggle"; exit 1; }
+          kaggle kernels push -p ${NOTEBOOK_DIR} || { echo "Failed to push notebook to Kaggle"; exit 1; }
